# Create a program that will play the “cows and bulls” game with the user. The game works like this:

# Randomly generate a 4-digit number. Ask the user to guess a 4-digit number(Digits should not be repeated). For every digit that the user guessed correctly in the correct place, they have a “cow”. For every digit the user guessed correctly in the wrong place is a “bull.” Every time the user makes a guess, tell them how many “cows” and “bulls” they have. Once the user guesses the correct number, the game is over. Keep track of the number of guesses the user makes throughout teh game and tell the user at the end.

# Say the number generated by the computer is 1038. An example interaction could look like this:
#   Welcome to the Cows and Bulls Game! 
#   Enter a number: 
#   >>> 1234
#   2 cows, 0 bulls
#   >>> 1250
#   1 cow, 1 bull
#   ...
# Until the user guesses the number.

import random


def generate_number():
    return str(random.randint(1000, 9999))

def count_cows_bulls(guess, number):
    cows = 0
    bulls = 0

    for i in range(4):
        if guess[i] == number[i]:
            cows +=1
        elif guess[i] in number:
            bulls +=1
    return cows, bulls



def play_game():
    number = generate_number()
    attempts = 0
    while True:
        guess = input("Enter a 4 digit number of your guess: ")
        attempts += 1
        cows, bulls = count_cows_bulls(guess, number)
        print(f"Cows: {cows}, Bulls: {bulls}")
        if cows == 4:
            print(f"Congratulations you have guessed the number in {attempts} attempts")

play_game()